### PR TITLE
Arrange chapters 2 and 3 and prepare others

### PR DESCRIPTION
**Pull request by franiglesias**
Chapters 2 and 3 are now ready

Some changes in another chapters, waiting for stabilizing book schema

### CODE REVIEW

**Comment by lex111** [comment]
Por favor resuelva el conflicto en manuscript/Book.txt

**Review by lex111 — CHANGES_REQUESTED** [review]
Por favor resuelva el conflicto en manuscript/Book.txt

**Review by lex111 — CHANGES_REQUESTED** [review]
Por favor resuelva el conflicto en manuscript/Book.txt

**Comment by franiglesias** [comment]
Resolved, thanks

**Review by lex111 — APPROVED** [review]

**Comment by lex111** [comment]
Gracias!

**Pull request merged**
